Vagrant.configure("2") do |config|
  config.vm.define "vm1" do |vm1|
    vm1.vm.box = "bento/ubuntu-22.04"
    vm1.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter"
    vm1.vm.hostname = "vm1"
    vm1.vm.synced_folder ".", "/lecture_4", type: "virtualbox"
    vm1.vm.provider "virtualbox" do |vb1|
      vb1.memory = "2048"
      vb1.cpus = 1
    end
    vm1.vm.provision "shell", inline: <<-SHELL
      sudo apt-get update
      sudo apt-get install -y nginx
    SHELL
  end
  config.vm.define "vm2" do |vm2|
      vm2.vm.box = "bento/ubuntu-22.04"
      vm2.vm.network "private_network", ip: "10.1.2.3", auto_config: true
      vm2.vm.hostname = "vm2"
      vm2.vm.synced_folder ".", "/lecture_4", type: "virtualbox"
      vm2.vm.provider "virtualbox" do |vb2|
        vb2.memory = "2048"
        vb2.cpus = 1
      end
      vm2.vm.provision "shell", path: "nginx.sh"
  end
  config.vm.define "vm3" do |vm3|
      vm3.vm.box = "bento/ubuntu-22.04"
      vm3.vm.network "public_network", ip: "192.168.0.111", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter"
      vm3.vm.hostname = "vm3"
      vm3.vm.synced_folder ".", "/lecture_4_v2", type: "virtualbox"
      vm3.vm.provider "virtualbox" do |vb3|
        vb3.memory = "2048"
        vb3.cpus = 1
      end
  end
  ["vm4", "vm5", "vm6"].each do |vm_all| 
    config.vm.define vm_all do |vm|
      vm.vm.box = "bento/ubuntu-22.04"
      vm.vm.network "public_network", bridge: "Qualcomm QCA9377 802.11ac Wireless Adapter" 
      vm.vm.synced_folder ".", "/lecture_4", type: "virtualbox"
      vm.vm.provider "virtualbox" do |vb|
      vb.memory = "2048"
      vb.cpus = 1
      end
      vm.vm.provision "shell", inline: <<-SHELL
        sudo apt-get update
        sudo apt-get install -y nginx
      SHELL
    end
  end
end