apiVersion: v1
kind: Pod
metadata:
  name: app-with-pvc
spec:
  containers:
  - name: app
    image: nginx:latest
    volumeMounts:
    - mountPath: "/data"
      name: app-storage
  volumes:
  - name: app-storage
    persistentVolumeClaim:
      claimName: ebs-pvc
