version: '3.8'

services:
  web:
    image: nginx
    volumes:
      - ./web-data/:/usr/share/nginx/html/
    networks:
      - appnet

  loadbalancer:
    image: nginx
    ports:
      - "8080:80" 
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf 
    networks:
      - appnet
  db:
    image: mysql
    environment:
      MYSQL_ROOT_USER: admin
      MYSQL_ROOT_PASSWORD: admin
    volumes:
      - ./db-data:/var/lib/mysql
      - ./db-init:/docker-entrypoint-initdb.d 
    networks:
      - appnet

  cache:
    image: redis
    networks:
      - appnet

volumes:
  db-data:
  web-data:

networks:
  appnet:
